project:
  type: default
  output-dir: ../docs/slides
  render:
    - "*.qmd"

format:
  revealjs:
    theme: simple
    slide-number: true
    chalkboard: true
    css: slides.css
    footer: "Math and Programming Camp, Dept. of Government, Georgetown University"
    smaller: true

editor: source
